#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -f /etc/hifiberry/players.d/analog.json
    rm -f /etc/hifiberry/players.d/icons/analog.svg
    rm -f /etc/configserver/conf.d/analog-recognition.json
    rm -f /etc/audiocontrol/players.d/analog.json
fi

#DEBHELPER#

exit 0
